# 1. Calculate the total revenue generated by two product categories in a store 

# Input: category1_revenue = np.array([500, 600, 700, 550]) 

# category2_revenue = np.array([450, 700, 800, 600]) 

# Output: Total Revenue: [ 950 1300 1500 1150] 

import numpy as np

# Step 1: Define the revenues for each product category using numpy arrays
category1_revenue = np.array([500, 600, 700, 550])  # Revenue for Category 1
category2_revenue = np.array([450, 700, 800, 600])  # Revenue for Category 2

# Step 2: Calculate the total revenue by adding the two arrays element-wise
total_revenue = category1_revenue + category2_revenue  # Total revenue for each time period

# Output the total revenue
print("Total Revenue:", total_revenue)

# Output:-

"""
Total Revenue: [ 950 1300 1500 1150]

"""
